version: '3'
services:
  user:
    build:
      context: ./User
    ports:
      - "3001:8080"
    command: node server.js
    env_file:
      - .env

  cart:
    build:
      context: ./Cart
    ports:
      - "3003:8080"
    command: node server.js  
    env_file:
      - .env

  product:
    build:
      context: ./Product
    ports:
      - "3002:8080"
    command: node server.js
    env_file:
      - .env
  
  frontend:
    build:
      context: ./front-end
    ports:
      - "3000:8080"
    command: npm run dev
    env_file:
      - .env
    depends_on:
      - user
      - cart
      - product
    
